services:
  notify.rabbitmq:
    image: rabbitmq:4-management
    restart: always
    hostname: notify-rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT}:15672'
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
